apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ocr
spec:  
  replicas: 1
  serviceName: ocr-statefulset-test
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      volumes:
      - name: ocr-statefulset-test
        flexVolume:
          driver: "fstab/cifs"
          fsType: "cifs"
          secretRef:
            name: "cifs-secret"
          options:
            networkPath: "//filcro27/K8s/ocr-statefulset-test"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
      containers:
      - name: ocr
        image: patrickcurl/tesseract-pwsh:latest
        imagePullPolicy: "Always"
        command:
        - pwsh
        - /scripts/OCR-statefulset.ps1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ocr-statefulset-test
          mountPath: "/OCR"
