apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ocr-statefulset
spec:
  replicas: 1
  serviceName: ocr-statefulset
  selector:
    matchLabels:
      app: ocr-statefulset
  template:
    metadata:
      name: ocr-statefulset
      labels:
        app: ocr-statefulset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: com.docker.ucp.manager
        effect: NoSchedule
      containers:
        - image: patrickcurl/tesseract-pwsh:latest
          name: ocr-statefulset
          securityContext:
            privileged: true
          command:
          - pwsh
          - /scripts/OCR-statefulset.ps1
          volumeMounts:
            - mountPath: /OCR
              name: ocr-statefulset
      volumes:
        - name: ocr-statefulset
          persistentVolumeClaim:
            claimName: ocr-statefulset
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-statefulset
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: ocr-statefulset
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocr-statefulset
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
   driver: fstab/cifs
   fsType: cifs
   options:
     mountOptions: 'file_mode=0770,dir_mode=0770'
     networkPath: //filcro27.advcro.local/K8s/ocr
   secretRef:
     name: cifs-secret