apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ocr
spec:  
  replicas: 1
  serviceName: ocr-statefulset
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      volumes:
      - name: ocr-statefulset
        persistentVolumeClaim:
          claimName: ocr-statefulset
      containers:
      - name: ocr
        image: patrickcurl/tesseract-pwsh:latest
        imagePullPolicy: "Always"
        command:
        - pwsh
        - /scripts/OCR-statefulset.ps1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ocr-statefulset
          mountPath: "/OCR"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-statefulset
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  volumeName: ocr-statefulset
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocr-statefulset
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
   driver: fstab/cifs
   fsType: cifs
   options:
     mountOptions: 'file_mode=0770,dir_mode=0770'
     networkPath: //filcro27.advcro.local/K8s/ocr
   secretRef:
     name: cifs-secret